import type { Metadata } from "next";
import { Play } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/custom/navbar";

const play = Play({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-play",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${play.variable} font-play`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
